name: Basic CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run application check script
        run: ./app/check_app.sh

      - name: Display index.html content
        run: cat app/index.html
        
      - name: Display secrets and variables
        env:
          MY_SECRET: ${{ secrets.FAKE_API_TOKEN }}
          MY_ENV: ${{ secrets.ENV_TYPE }}
          CUSTOM_VAR: "Ceci est une variable publique non-secrete"
        run: |
          echo "OS du Runner : $RUNNER_OS"
          echo "Variable personnalisee : $CUSTOM_VAR"
          echo "Type d'environnement : $MY_ENV"
          echo "Secret API : $MY_SECRET"